### ISSUE TITLE
Cannot download a nightly version

### ISSUE THREAD

**Issue by zyguan** [c4pt0r/tiup#20]
https://github.com/c4pt0r/tiup/blob/e2be5cd1df4f19e52421acd1783e595a4ffb7637/pkg/meta/repository.go#L106-L113

Is that by design? @lonng

**Comment by lonng** [comment]
Yes, our mirror structure will follow the naming convention.

**Comment by lonng** [comment]
there is no nightly tarball in mirror now.

**Comment by zyguan** [comment]
Got it.
